# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modelbuilder.ui'
#
# Created: Tue May 03 16:58:28 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ModelBuilder(object):
    def setupUi(self, ModelBuilder):
        ModelBuilder.setObjectName(_fromUtf8("ModelBuilder"))
        ModelBuilder.resize(879, 503)
        self.pushButton_Execute = QtGui.QPushButton(ModelBuilder)
        self.pushButton_Execute.setGeometry(QtCore.QRect(730, 470, 141, 32))
        self.pushButton_Execute.setAutoDefault(False)
        self.pushButton_Execute.setObjectName(_fromUtf8("pushButton_Execute"))
        self.lineEdit_path = QtGui.QLineEdit(ModelBuilder)
        self.lineEdit_path.setGeometry(QtCore.QRect(10, 470, 621, 22))
        self.lineEdit_path.setText(_fromUtf8(""))
        self.lineEdit_path.setObjectName(_fromUtf8("lineEdit_path"))
        self.tableView = QtGui.QTableView(ModelBuilder)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 701, 451))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.lineEdit_target = QtGui.QLineEdit(ModelBuilder)
        self.lineEdit_target.setGeometry(QtCore.QRect(730, 430, 61, 22))
        self.lineEdit_target.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_target.setObjectName(_fromUtf8("lineEdit_target"))
        self.label_6 = QtGui.QLabel(ModelBuilder)
        self.label_6.setGeometry(QtCore.QRect(730, 410, 101, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_pickle = QtGui.QPushButton(ModelBuilder)
        self.pushButton_pickle.setEnabled(False)
        self.pushButton_pickle.setGeometry(QtCore.QRect(800, 430, 71, 32))
        self.pushButton_pickle.setAutoDefault(False)
        self.pushButton_pickle.setObjectName(_fromUtf8("pushButton_pickle"))
        self.pushButton_find = QtGui.QPushButton(ModelBuilder)
        self.pushButton_find.setEnabled(True)
        self.pushButton_find.setGeometry(QtCore.QRect(640, 470, 71, 32))
        self.pushButton_find.setAutoDefault(False)
        self.pushButton_find.setObjectName(_fromUtf8("pushButton_find"))
        self.groupBox = QtGui.QGroupBox(ModelBuilder)
        self.groupBox.setGeometry(QtCore.QRect(720, 20, 151, 71))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButton_validation_CV = QtGui.QRadioButton(self.groupBox)
        self.radioButton_validation_CV.setGeometry(QtCore.QRect(10, 40, 91, 20))
        self.radioButton_validation_CV.setChecked(False)
        self.radioButton_validation_CV.setAutoExclusive(True)
        self.radioButton_validation_CV.setObjectName(_fromUtf8("radioButton_validation_CV"))
        self.radioButton_validation_year = QtGui.QRadioButton(self.groupBox)
        self.radioButton_validation_year.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.radioButton_validation_year.setChecked(True)
        self.radioButton_validation_year.setAutoExclusive(True)
        self.radioButton_validation_year.setObjectName(_fromUtf8("radioButton_validation_year"))
        self.lineEdit_year = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_year.setEnabled(True)
        self.lineEdit_year.setGeometry(QtCore.QRect(100, 20, 41, 20))
        self.lineEdit_year.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_year.setObjectName(_fromUtf8("lineEdit_year"))
        self.lineEdit_CV_folds = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_CV_folds.setEnabled(True)
        self.lineEdit_CV_folds.setGeometry(QtCore.QRect(100, 40, 41, 20))
        self.lineEdit_CV_folds.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CV_folds.setObjectName(_fromUtf8("lineEdit_CV_folds"))
        self.groupBox_2 = QtGui.QGroupBox(ModelBuilder)
        self.groupBox_2.setGeometry(QtCore.QRect(720, 320, 151, 81))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.radioButton_PLS = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_PLS.setGeometry(QtCore.QRect(10, 20, 131, 20))
        self.radioButton_PLS.setChecked(True)
        self.radioButton_PLS.setAutoExclusive(True)
        self.radioButton_PLS.setObjectName(_fromUtf8("radioButton_PLS"))
        self.radioButton_Boost = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_Boost.setGeometry(QtCore.QRect(10, 40, 141, 20))
        self.radioButton_Boost.setChecked(False)
        self.radioButton_Boost.setAutoExclusive(True)
        self.radioButton_Boost.setObjectName(_fromUtf8("radioButton_Boost"))
        self.radioButton_Logistic = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_Logistic.setGeometry(QtCore.QRect(10, 60, 141, 20))
        self.radioButton_Logistic.setChecked(False)
        self.radioButton_Logistic.setAutoExclusive(True)
        self.radioButton_Logistic.setObjectName(_fromUtf8("radioButton_Logistic"))
        self.groupBox_3 = QtGui.QGroupBox(ModelBuilder)
        self.groupBox_3.setGeometry(QtCore.QRect(720, 230, 151, 81))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.checkBox_bFalseNeg = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_bFalseNeg.setGeometry(QtCore.QRect(10, 20, 121, 20))
        self.checkBox_bFalseNeg.setObjectName(_fromUtf8("checkBox_bFalseNeg"))
        self.checkBox_bFalseNegRate = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_bFalseNegRate.setGeometry(QtCore.QRect(10, 40, 141, 20))
        self.checkBox_bFalseNegRate.setChecked(True)
        self.checkBox_bFalseNegRate.setObjectName(_fromUtf8("checkBox_bFalseNegRate"))
        self.checkBox_bNDR = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_bNDR.setGeometry(QtCore.QRect(10, 60, 151, 20))
        self.checkBox_bNDR.setObjectName(_fromUtf8("checkBox_bNDR"))
        self.groupBox_4 = QtGui.QGroupBox(ModelBuilder)
        self.groupBox_4.setGeometry(QtCore.QRect(720, 160, 151, 61))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.checkBox_tProps = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_tProps.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.checkBox_tProps.setObjectName(_fromUtf8("checkBox_tProps"))
        self.checkBox_tCounts = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_tCounts.setGeometry(QtCore.QRect(10, 40, 87, 20))
        self.checkBox_tCounts.setChecked(True)
        self.checkBox_tCounts.setObjectName(_fromUtf8("checkBox_tCounts"))
        self.groupBox_5 = QtGui.QGroupBox(ModelBuilder)
        self.groupBox_5.setGeometry(QtCore.QRect(720, 100, 151, 51))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.lineEdit_specificities = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_specificities.setGeometry(QtCore.QRect(10, 20, 131, 22))
        self.lineEdit_specificities.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_specificities.setObjectName(_fromUtf8("lineEdit_specificities"))

        self.retranslateUi(ModelBuilder)
        QtCore.QMetaObject.connectSlotsByName(ModelBuilder)

    def retranslateUi(self, ModelBuilder):
        ModelBuilder.setWindowTitle(QtGui.QApplication.translate("ModelBuilder", "ModelBuilder", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Execute.setText(QtGui.QApplication.translate("ModelBuilder", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_path.setPlaceholderText(QtGui.QApplication.translate("ModelBuilder", "Data source...", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_target.setText(QtGui.QApplication.translate("ModelBuilder", "LogEC", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_target.setPlaceholderText(QtGui.QApplication.translate("ModelBuilder", "<value>, <value>, <value>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ModelBuilder", "Target:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pickle.setText(QtGui.QApplication.translate("ModelBuilder", "Pickle", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_find.setText(QtGui.QApplication.translate("ModelBuilder", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ModelBuilder", "Validation", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_validation_CV.setText(QtGui.QApplication.translate("ModelBuilder", "Random folds:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_validation_year.setText(QtGui.QApplication.translate("ModelBuilder", "Year:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_year.setText(QtGui.QApplication.translate("ModelBuilder", "2010", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_year.setPlaceholderText(QtGui.QApplication.translate("ModelBuilder", "year...", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_CV_folds.setText(QtGui.QApplication.translate("ModelBuilder", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_CV_folds.setPlaceholderText(QtGui.QApplication.translate("ModelBuilder", "year...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ModelBuilder", "Learning Method", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_PLS.setText(QtGui.QApplication.translate("ModelBuilder", "PLS regression", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Boost.setText(QtGui.QApplication.translate("ModelBuilder", "Trees w/ boosting", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Logistic.setText(QtGui.QApplication.translate("ModelBuilder", "Logistic regression", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ModelBuilder", "Balance by", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_bFalseNeg.setText(QtGui.QApplication.translate("ModelBuilder", "False negatives", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_bFalseNegRate.setText(QtGui.QApplication.translate("ModelBuilder", "False negative rate", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_bNDR.setText(QtGui.QApplication.translate("ModelBuilder", "Non-discovery rate", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("ModelBuilder", "Threshold by:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_tProps.setText(QtGui.QApplication.translate("ModelBuilder", "Proportions", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_tCounts.setText(QtGui.QApplication.translate("ModelBuilder", "Counts", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("ModelBuilder", "Specificities", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_specificities.setText(QtGui.QApplication.translate("ModelBuilder", "0.89, 0.90, 0.91", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_specificities.setPlaceholderText(QtGui.QApplication.translate("ModelBuilder", "<value>, <value>, <value>", None, QtGui.QApplication.UnicodeUTF8))

