# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modelbuilder.ui'
#
# Created: Wed Mar 16 15:08:52 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ModelBuilder(object):
    def setupUi(self, ModelBuilder):
        ModelBuilder.setObjectName(_fromUtf8("ModelBuilder"))
        ModelBuilder.resize(869, 503)
        self.pushButton_Execute = QtGui.QPushButton(ModelBuilder)
        self.pushButton_Execute.setGeometry(QtCore.QRect(720, 470, 141, 32))
        self.pushButton_Execute.setAutoDefault(False)
        self.pushButton_Execute.setObjectName(_fromUtf8("pushButton_Execute"))
        self.radioButton_Logistic = QtGui.QRadioButton(ModelBuilder)
        self.radioButton_Logistic.setGeometry(QtCore.QRect(720, 370, 141, 20))
        self.radioButton_Logistic.setChecked(False)
        self.radioButton_Logistic.setObjectName(_fromUtf8("radioButton_Logistic"))
        self.radioButton_Boost = QtGui.QRadioButton(ModelBuilder)
        self.radioButton_Boost.setGeometry(QtCore.QRect(720, 350, 141, 20))
        self.radioButton_Boost.setChecked(False)
        self.radioButton_Boost.setObjectName(_fromUtf8("radioButton_Boost"))
        self.radioButton_PLS = QtGui.QRadioButton(ModelBuilder)
        self.radioButton_PLS.setGeometry(QtCore.QRect(720, 330, 131, 20))
        self.radioButton_PLS.setChecked(True)
        self.radioButton_PLS.setObjectName(_fromUtf8("radioButton_PLS"))
        self.lineEdit_path = QtGui.QLineEdit(ModelBuilder)
        self.lineEdit_path.setGeometry(QtCore.QRect(10, 470, 621, 22))
        self.lineEdit_path.setText(_fromUtf8(""))
        self.lineEdit_path.setObjectName(_fromUtf8("lineEdit_path"))
        self.tableView = QtGui.QTableView(ModelBuilder)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 701, 451))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.checkBox_tCounts = QtGui.QCheckBox(ModelBuilder)
        self.checkBox_tCounts.setGeometry(QtCore.QRect(720, 170, 87, 20))
        self.checkBox_tCounts.setChecked(True)
        self.checkBox_tCounts.setObjectName(_fromUtf8("checkBox_tCounts"))
        self.checkBox_tProps = QtGui.QCheckBox(ModelBuilder)
        self.checkBox_tProps.setGeometry(QtCore.QRect(720, 150, 101, 20))
        self.checkBox_tProps.setObjectName(_fromUtf8("checkBox_tProps"))
        self.label = QtGui.QLabel(ModelBuilder)
        self.label.setGeometry(QtCore.QRect(720, 130, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.checkBox_bFalseNegRate = QtGui.QCheckBox(ModelBuilder)
        self.checkBox_bFalseNegRate.setGeometry(QtCore.QRect(720, 250, 141, 20))
        self.checkBox_bFalseNegRate.setChecked(True)
        self.checkBox_bFalseNegRate.setObjectName(_fromUtf8("checkBox_bFalseNegRate"))
        self.checkBox_bFalseNeg = QtGui.QCheckBox(ModelBuilder)
        self.checkBox_bFalseNeg.setGeometry(QtCore.QRect(720, 230, 121, 20))
        self.checkBox_bFalseNeg.setObjectName(_fromUtf8("checkBox_bFalseNeg"))
        self.label_2 = QtGui.QLabel(ModelBuilder)
        self.label_2.setGeometry(QtCore.QRect(720, 210, 91, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.checkBox_bNDR = QtGui.QCheckBox(ModelBuilder)
        self.checkBox_bNDR.setGeometry(QtCore.QRect(720, 270, 151, 20))
        self.checkBox_bNDR.setObjectName(_fromUtf8("checkBox_bNDR"))
        self.label_3 = QtGui.QLabel(ModelBuilder)
        self.label_3.setGeometry(QtCore.QRect(720, 310, 121, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(ModelBuilder)
        self.label_4.setGeometry(QtCore.QRect(720, 10, 101, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_year = QtGui.QLineEdit(ModelBuilder)
        self.lineEdit_year.setEnabled(True)
        self.lineEdit_year.setGeometry(QtCore.QRect(720, 30, 51, 22))
        self.lineEdit_year.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_year.setObjectName(_fromUtf8("lineEdit_year"))
        self.label_5 = QtGui.QLabel(ModelBuilder)
        self.label_5.setGeometry(QtCore.QRect(720, 70, 101, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_specificities = QtGui.QLineEdit(ModelBuilder)
        self.lineEdit_specificities.setGeometry(QtCore.QRect(720, 90, 141, 22))
        self.lineEdit_specificities.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_specificities.setObjectName(_fromUtf8("lineEdit_specificities"))
        self.line = QtGui.QFrame(ModelBuilder)
        self.line.setGeometry(QtCore.QRect(720, 49, 141, 31))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(ModelBuilder)
        self.line_2.setGeometry(QtCore.QRect(720, 110, 141, 31))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(ModelBuilder)
        self.line_3.setGeometry(QtCore.QRect(720, 190, 141, 21))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(ModelBuilder)
        self.line_4.setGeometry(QtCore.QRect(720, 290, 141, 21))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(ModelBuilder)
        self.line_5.setGeometry(QtCore.QRect(720, 390, 141, 21))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.lineEdit_target = QtGui.QLineEdit(ModelBuilder)
        self.lineEdit_target.setGeometry(QtCore.QRect(720, 430, 61, 22))
        self.lineEdit_target.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_target.setObjectName(_fromUtf8("lineEdit_target"))
        self.label_6 = QtGui.QLabel(ModelBuilder)
        self.label_6.setGeometry(QtCore.QRect(720, 410, 101, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_pickle = QtGui.QPushButton(ModelBuilder)
        self.pushButton_pickle.setEnabled(False)
        self.pushButton_pickle.setGeometry(QtCore.QRect(790, 430, 71, 32))
        self.pushButton_pickle.setAutoDefault(False)
        self.pushButton_pickle.setObjectName(_fromUtf8("pushButton_pickle"))
        self.pushButton_find = QtGui.QPushButton(ModelBuilder)
        self.pushButton_find.setEnabled(True)
        self.pushButton_find.setGeometry(QtCore.QRect(640, 470, 71, 32))
        self.pushButton_find.setAutoDefault(False)
        self.pushButton_find.setObjectName(_fromUtf8("pushButton_find"))

        self.retranslateUi(ModelBuilder)
        QtCore.QMetaObject.connectSlotsByName(ModelBuilder)

    def retranslateUi(self, ModelBuilder):
        ModelBuilder.setWindowTitle(QtGui.QApplication.translate("ModelBuilder", "ModelBuilder", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Execute.setText(QtGui.QApplication.translate("ModelBuilder", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Logistic.setText(QtGui.QApplication.translate("ModelBuilder", "Logistic regression", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Boost.setText(QtGui.QApplication.translate("ModelBuilder", "Trees w/ boosting", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_PLS.setText(QtGui.QApplication.translate("ModelBuilder", "PLS regression", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_path.setPlaceholderText(QtGui.QApplication.translate("ModelBuilder", "Data source...", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_tCounts.setText(QtGui.QApplication.translate("ModelBuilder", "Counts", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_tProps.setText(QtGui.QApplication.translate("ModelBuilder", "Proportions", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ModelBuilder", "Threshold by:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_bFalseNegRate.setText(QtGui.QApplication.translate("ModelBuilder", "False negative rate", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_bFalseNeg.setText(QtGui.QApplication.translate("ModelBuilder", "False negatives", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ModelBuilder", "Balance by:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_bNDR.setText(QtGui.QApplication.translate("ModelBuilder", "Non-discovery rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ModelBuilder", "Learning method", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ModelBuilder", "Validation year:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_year.setText(QtGui.QApplication.translate("ModelBuilder", "2010", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_year.setPlaceholderText(QtGui.QApplication.translate("ModelBuilder", "year...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ModelBuilder", "Specificities:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_specificities.setText(QtGui.QApplication.translate("ModelBuilder", "0.89, 0.90, 0.91", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_specificities.setPlaceholderText(QtGui.QApplication.translate("ModelBuilder", "<value>, <value>, <value>", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_target.setText(QtGui.QApplication.translate("ModelBuilder", "LogEC", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_target.setPlaceholderText(QtGui.QApplication.translate("ModelBuilder", "<value>, <value>, <value>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ModelBuilder", "Target:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pickle.setText(QtGui.QApplication.translate("ModelBuilder", "Pickle", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_find.setText(QtGui.QApplication.translate("ModelBuilder", "Find", None, QtGui.QApplication.UnicodeUTF8))

