# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modeluser.ui'
#
# Created: Wed Mar  9 11:10:23 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ModelUser(object):
    def setupUi(self, ModelUser):
        ModelUser.setObjectName(_fromUtf8("ModelUser"))
        ModelUser.resize(339, 487)
        self.pushButton_Wild = QtGui.QPushButton(ModelUser)
        self.pushButton_Wild.setGeometry(QtCore.QRect(20, 410, 114, 32))
        self.pushButton_Wild.setObjectName(_fromUtf8("pushButton_Wild"))
        self.lineEdit_turbidity = QtGui.QLineEdit(ModelUser)
        self.lineEdit_turbidity.setGeometry(QtCore.QRect(20, 70, 113, 22))
        self.lineEdit_turbidity.setObjectName(_fromUtf8("lineEdit_turbidity"))
        self.lineEdit_24_precip = QtGui.QLineEdit(ModelUser)
        self.lineEdit_24_precip.setGeometry(QtCore.QRect(20, 100, 113, 22))
        self.lineEdit_24_precip.setObjectName(_fromUtf8("lineEdit_24_precip"))
        self.lineEdit_48_precip = QtGui.QLineEdit(ModelUser)
        self.lineEdit_48_precip.setGeometry(QtCore.QRect(20, 130, 113, 22))
        self.lineEdit_48_precip.setObjectName(_fromUtf8("lineEdit_48_precip"))
        self.lineEdit_water_temp = QtGui.QLineEdit(ModelUser)
        self.lineEdit_water_temp.setGeometry(QtCore.QRect(20, 220, 113, 22))
        self.lineEdit_water_temp.setObjectName(_fromUtf8("lineEdit_water_temp"))
        self.lineEdit_flow_mgd = QtGui.QLineEdit(ModelUser)
        self.lineEdit_flow_mgd.setGeometry(QtCore.QRect(20, 190, 113, 22))
        self.lineEdit_flow_mgd.setObjectName(_fromUtf8("lineEdit_flow_mgd"))
        self.lineEdit_air_temp = QtGui.QLineEdit(ModelUser)
        self.lineEdit_air_temp.setGeometry(QtCore.QRect(20, 280, 113, 22))
        self.lineEdit_air_temp.setObjectName(_fromUtf8("lineEdit_air_temp"))
        self.lineEdit_wind = QtGui.QLineEdit(ModelUser)
        self.lineEdit_wind.setGeometry(QtCore.QRect(20, 310, 113, 22))
        self.lineEdit_wind.setObjectName(_fromUtf8("lineEdit_wind"))
        self.lineEdit_wave_height = QtGui.QLineEdit(ModelUser)
        self.lineEdit_wave_height.setGeometry(QtCore.QRect(20, 250, 113, 22))
        self.lineEdit_wave_height.setObjectName(_fromUtf8("lineEdit_wave_height"))
        self.lineEdit_level = QtGui.QLineEdit(ModelUser)
        self.lineEdit_level.setGeometry(QtCore.QRect(20, 340, 113, 22))
        self.lineEdit_level.setObjectName(_fromUtf8("lineEdit_level"))
        self.lineEdit_julian = QtGui.QLineEdit(ModelUser)
        self.lineEdit_julian.setGeometry(QtCore.QRect(20, 40, 113, 22))
        self.lineEdit_julian.setObjectName(_fromUtf8("lineEdit_julian"))
        self.lineEdit_year = QtGui.QLineEdit(ModelUser)
        self.lineEdit_year.setGeometry(QtCore.QRect(20, 10, 113, 22))
        self.lineEdit_year.setObjectName(_fromUtf8("lineEdit_year"))
        self.lineEdit_flow_total = QtGui.QLineEdit(ModelUser)
        self.lineEdit_flow_total.setGeometry(QtCore.QRect(20, 160, 113, 22))
        self.lineEdit_flow_total.setObjectName(_fromUtf8("lineEdit_flow_total"))
        self.lineEdit_x3qtr = QtGui.QLineEdit(ModelUser)
        self.lineEdit_x3qtr.setGeometry(QtCore.QRect(20, 370, 113, 22))
        self.lineEdit_x3qtr.setObjectName(_fromUtf8("lineEdit_x3qtr"))
        self.pushButton_predict = QtGui.QPushButton(ModelUser)
        self.pushButton_predict.setGeometry(QtCore.QRect(170, 410, 131, 32))
        self.pushButton_predict.setObjectName(_fromUtf8("pushButton_predict"))
        self.label = QtGui.QLabel(ModelUser)
        self.label.setGeometry(QtCore.QRect(160, 450, 71, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_output = QtGui.QLabel(ModelUser)
        self.label_output.setGeometry(QtCore.QRect(240, 450, 62, 16))
        self.label_output.setText(_fromUtf8(""))
        self.label_output.setObjectName(_fromUtf8("label_output"))
        self.label_3 = QtGui.QLabel(ModelUser)
        self.label_3.setGeometry(QtCore.QRect(150, 370, 71, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(ModelUser)
        self.label_4.setGeometry(QtCore.QRect(150, 250, 151, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(ModelUser)
        self.label_5.setGeometry(QtCore.QRect(150, 280, 151, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(ModelUser)
        self.label_6.setGeometry(QtCore.QRect(150, 340, 151, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(ModelUser)
        self.label_7.setGeometry(QtCore.QRect(150, 220, 161, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(ModelUser)
        self.label_8.setGeometry(QtCore.QRect(150, 310, 131, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(ModelUser)
        self.label_9.setGeometry(QtCore.QRect(150, 190, 91, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(ModelUser)
        self.label_10.setGeometry(QtCore.QRect(150, 160, 181, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(ModelUser)
        self.label_11.setGeometry(QtCore.QRect(150, 100, 161, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(ModelUser)
        self.label_12.setGeometry(QtCore.QRect(150, 40, 71, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(ModelUser)
        self.label_13.setGeometry(QtCore.QRect(150, 130, 171, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(ModelUser)
        self.label_14.setGeometry(QtCore.QRect(150, 70, 101, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(ModelUser)
        self.label_15.setGeometry(QtCore.QRect(150, 10, 71, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))

        self.retranslateUi(ModelUser)
        QtCore.QMetaObject.connectSlotsByName(ModelUser)

    def retranslateUi(self, ModelUser):
        ModelUser.setWindowTitle(QtGui.QApplication.translate("ModelUser", "ModelUser", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Wild.setText(QtGui.QApplication.translate("ModelUser", "Select model", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_turbidity.setText(QtGui.QApplication.translate("ModelUser", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_24_precip.setText(QtGui.QApplication.translate("ModelUser", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_48_precip.setText(QtGui.QApplication.translate("ModelUser", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_water_temp.setText(QtGui.QApplication.translate("ModelUser", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_flow_mgd.setText(QtGui.QApplication.translate("ModelUser", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_air_temp.setText(QtGui.QApplication.translate("ModelUser", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_wind.setText(QtGui.QApplication.translate("ModelUser", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_wave_height.setText(QtGui.QApplication.translate("ModelUser", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_level.setText(QtGui.QApplication.translate("ModelUser", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_julian.setText(QtGui.QApplication.translate("ModelUser", "150", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_year.setText(QtGui.QApplication.translate("ModelUser", "2010", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_flow_total.setText(QtGui.QApplication.translate("ModelUser", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_x3qtr.setText(QtGui.QApplication.translate("ModelUser", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_predict.setText(QtGui.QApplication.translate("ModelUser", "Make prediction", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ModelUser", "Prediction:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ModelUser", "X3qtr", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ModelUser", "Wave height (ft)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ModelUser", "Avg air temp (deg F)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ModelUser", "Lake level (Milwaukee)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ModelUser", "Avg water temp (deg F)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ModelUser", "Wind speed (mph)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ModelUser", "Flow (mgd)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ModelUser", "Yesterday\'s total flow (x100)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("ModelUser", "24 hour total rainfall (in)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("ModelUser", "Julian date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("ModelUser", "48 hour total rainfall (in)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("ModelUser", "Turbidity (NTU)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("ModelUser", "Year", None, QtGui.QApplication.UnicodeUTF8))

